name: Error report
description: Report an error spit by YAGPDB or unexpected behavior from custom commands.
labels: ["Error"]
body:
- type: dropdown
  attributes:
    label: Custom command
    description: Select the Custom Command you are having issues with
    options:
      - Avatar
      - Custom Command Template
      - Extract
      - Forum Automatic Help
      - Forum Post Logging
      - Forum Tools
      - Pet
      - Public Gearbot Infractions
      - Redirect
      - Report
      - Restrict
      - Swift AutoModeration
      - Swift Mute
      - Todo
      - Translate
  validations:
    required: true
- type: textarea
  attributes:
    label: Description
    description: Copy-paste the error here, or explain what the issue is.
  validations:
     required: true
