name: Error report
description: Report an error spit by YAGPDB or unexpected behavior from custom commands.
labels: ["Error"]
body:
- type: dropdown
  attributes:
    label: Custom command
    description: Select the Custom Command you are having issues with
    options:
      - CC: Avatar
      - CC: Custom Command Template
      - CC: Extract
      - CC: Forum Automatic Help
      - CC: Forum Post Logging
      - CC: Forum Tools
      - CC: Pet
      - CC: Public Gearbot Infractions
      - CC: Redirect
      - CC: Report
      - CC: Restrict
      - CC: Swift AutoModeration
      - CC: Swift Mute
      - CC: Todo
      - CC: Translate
  validations:
    required: true
- type: textarea
    attributes:
      label: Description
      description: Copy-paste the error here, or explain what the issue is.
    validations:
      required: true
