name: Suggestion
description: Suggest a new custom command, an improvement to an existing one, or something related to the repository.
labels: ["Suggestion"]

body:
  - type: dropdown
    id: target_area
    attributes:
      label: What is this suggestion related to?
      options:
        - Repository
        - New CC or SN
        - Avatar
        - Custom Command Indent
        - Custom Command Template
        - Embed Creator
        - Extract
        - Forum Automatic Help
        - Forum Automatic Messages
        - Forum Post Logging
        - Forum Tools
        - Generate Infraction Reason
        - Pet
        - Public Gearbot Infractions
        - Redirect
        - Report
        - Restrict
        - Swift AutoModeration
        - Swift Mute
        - Todo
        - Translate
    validations:
      required: true

  - type: textarea
    id: suggestion_details
    attributes:
      label: Suggestion Details
      description: Describe your idea or improvement.
    validations:
      required: true
